require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.mason")
require("plugins.blink")
require("plugins.tressiter")
-- После nvim-treesitter (kulala_http) и blink (capabilities для LSP)
require("plugins.kulala")
require("plugins.which-key")
require("plugins.autopairs")
-- require("plugins.indent")
-- require("plugins.telescope")
require("plugins.quicklist-improve")
require("plugins.flash")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.snacs")
require("plugins.go")
require("plugins.multicursor")
require("plugins.grug-far")
require("plugins.todo-comments")
require("plugins.ssh")
require("plugins.luasnip")
require("plugins.dadbod")
