require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.mason")
require("plugins.blink")
require("plugins.tressiter")
require("plugins.which-key")
require("plugins.autopairs")
-- require("plugins.indent")
-- require("plugins.telescope")
require("plugins.quicklist-improve")
require("plugins.flash")
require("plugins.nvim-tree")
require("plugins.snacs")
